const fs = require("fs");
const chron = require("../chron");
const updateTask = require("../UpdateTask");
const getModifiedCategories = require("../modifiedCategories");

const daysOfWeek = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

const categories = [
  {
    _id: "68b6fa7c4f1072ac4c787891",
    name: "Vision",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 1,
    done: 0,
    notDone: 7,
    total: 7,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "ડ્રીમ પાર કામ કઈરું?",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 1,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dacc",
      },
      {
        name: "1.5M પર કામ કઈરું?",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 2,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dacd",
      },
      {
        name: "Algorithmic Proficiency",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 3,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dace",
      },
      {
        name: "તાણ અને મન થી સુખી",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 4,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dacf",
      },
      {
        name: "1 ડગલું happiness, contentment અને gratitude તરફ",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 5,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dad0",
      },
      {
        name: "ભગવાન સાથે સંબંધ બાંધ્યો?",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 6,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dad1",
      },
      {
        name: "સૌ મોટા છે અને મારે શીખવું છે",
        notes: "",
        done: false,
        canBeRepeated: true,
        priority: 7,
        when: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
        _id: "68b71662d16a8c51f998dad2",
      },
    ],
  },
  {
    _id: "68b717a3d16a8c51f998db0e",
    name: "Address Change",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 2,
    done: 0,
    notDone: 5,
    total: 5,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "Mauli verify address with USPS",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 1,
        _id: "68b71804d16a8c51f998db69",
      },
      {
        name: "Bristol west address update",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 2,
        _id: "68b71804d16a8c51f998db6a",
      },
      {
        name: "Dhruv DL address update",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 3,
        _id: "68b71804d16a8c51f998db6b",
      },
      {
        name: "Mauli DL address update",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 4,
        _id: "68b71804d16a8c51f998db6c",
      },
      {
        name: "Dhruv verify address with USPS",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 5,
        _id: "68b71804d16a8c51f998db68",
      },
    ],
  },
  {
    _id: "68b71822d16a8c51f998db88",
    name: "Finance",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 3,
    done: 1,
    notDone: 8,
    total: 9,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "Close Saphire Reserve",
        notes: "Charging 700$",
        done: false,
        canBeRepeated: false,
        priority: 1,
        _id: "68b718c4d16a8c51f998dbf3",
      },
      {
        name: "Dhruv Commuter Benefit",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 2,
        _id: "68b718c4d16a8c51f998dbf4",
      },
      {
        name: "Mauli pay CIBC 4 cents",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 3,
        _id: "68b718c4d16a8c51f998dbf5",
      },
      {
        name: "Maa pending payments",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 4,
        _id: "68b718c4d16a8c51f998dbf6",
      },
      {
        name: "Mauli Paycheck Deposit",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 5,
        _id: "68b718c4d16a8c51f998dbf7",
      },
      {
        name: "Walmart stools refund",
        notes: "Stools - 108.74 , returned on 9/2\nInsurance - 12",
        done: false,
        canBeRepeated: false,
        priority: 6,
        _id: "68b72065d16a8c51f998dc81",
      },
      {
        name: "Get deposit of Xchange",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 7,
        _id: "68b72105d16a8c51f998dce1",
      },
      {
        name: "Check if payment needs to be made for water",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 8,
        _id: "68b723058b9dfef4a3244ac3",
      },
      {
        name: "Send money to Maa",
        notes: "",
        done: true,
        canBeRepeated: true,
        priority: 9,
        when: "15",
        _id: "68b718c4d16a8c51f998dbf8",
      },
    ],
  },
  {
    _id: "68b718e4d16a8c51f998dc18",
    name: "Home Sweet Home",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 4,
    done: 0,
    notDone: 10,
    total: 10,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "TV",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 1,
        _id: "68b722eb8b9dfef4a3244ab2",
      },
      {
        name: "Sofa Fix",
        notes: "Address Updated",
        done: false,
        canBeRepeated: false,
        priority: 2,
        _id: "68b722eb8b9dfef4a3244aaf",
      },
      {
        name: "Check king mattress",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 3,
        _id: "68b7211dd16a8c51f998dced",
      },
      {
        name: "Xfinity Refund",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 4,
        _id: "68b722eb8b9dfef4a3244ab0",
      },
      {
        name: "Exhaust fix",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 5,
        _id: "68b722eb8b9dfef4a3244ab1",
      },
      {
        name: "Order cover for chair legs",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 6,
        _id: "68b72b3b8b9dfef4a3244bdf",
      },
      {
        name: "Get Mail",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 7,
        _id: "68bee399b06155f08c67f9f9",
      },
      {
        name: "Clean washroom",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 8,
        _id: "68bee399b06155f08c67f9fa",
      },
      {
        name: "Vaccum bedroom",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 9,
        _id: "68bee399b06155f08c67f9fb",
      },
      {
        name: "Mailbox keys",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 10,
        _id: "68b7211dd16a8c51f998dcec",
      },
    ],
  },
  {
    _id: "68b723168b9dfef4a3244af2",
    name: "Health",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 5,
    done: 0,
    notDone: 4,
    total: 4,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "Papa teeth",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 1,
        _id: "68b7232c8b9dfef4a3244b63",
      },
      {
        name: "Dhruv annual physical",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 2,
        _id: "68b7232c8b9dfef4a3244b64",
      },
      {
        name: "Mauli - Annual Physical",
        notes: "- Call Jasmeet for aetna update\n- Get appointment",
        done: false,
        canBeRepeated: false,
        priority: 3,
        _id: "68bb0b220dddb11274be7a32",
      },
      {
        name: "Mauli specks",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 4,
        _id: "68bda913bc2c95d0c8443f5e",
      },
    ],
  },
  {
    _id: "68b716d2d16a8c51f998dae3",
    name: "Walmart",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 6,
    done: 0,
    notDone: 3,
    total: 3,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "Check if discount possible for gym",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 1,
        _id: "68b71730d16a8c51f998daff",
      },
      {
        name: "Get monitor fixed",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 2,
        _id: "68b718add16a8c51f998dbee",
      },
      {
        name: "Paycheck routing",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 3,
        when: "2025-09-12T01:39:00.000Z",
        _id: "68b71730d16a8c51f998db00",
      },
    ],
  },
  {
    _id: "68b84f28f7e75e4594fa8281",
    name: "Mauli Bday",
    color: "rgba(255, 255, 255, 0.1)",
    border: "rgba(255, 255, 255, 0.8)",
    priority: 7,
    done: 0,
    notDone: 2,
    total: 2,
    isMarkedDone: false,
    __v: 0,
    tasks: [
      {
        name: "Farm Experience",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 1,
        _id: "68b84f7bf7e75e4594fa8333",
      },
      {
        name: "Plan Hike",
        notes: "",
        done: false,
        canBeRepeated: false,
        priority: 2,
        _id: "68b84f7bf7e75e4594fa8334",
      },
    ],
  },
];

const result = updateTask(
  categories,
  "68b717a3d16a8c51f998db0e",
  "Dhruv verify address with USPS",
  {
    name: "Dhruv verify address with USPS",
    notes: "",
    done: false,
    canBeRepeated: true,
    priority: 1,
    _id: "68b71804d16a8c51f998db68",
    when: "2025-09-12T01:39:00.000Z",
  }
);

const result1 = getModifiedCategories(categories, result);

fs.writeFileSync("output.json", JSON.stringify(result1, null, 2));
